server:
  port: 8080
spring:
  application:
    name: cloud-consumer-order
  #zipkin配置
  zipkin:
    base-url: http://192.168.44.130:9411 # 指定zipkin地址
    sleuth:
      sampler:
        # 采样率介于0~1之间，1则表示全部采集
        probability: 1
#服务入驻
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://7001.cn.utools.club/eureka,https://7002.cn.utools.club/eureka