server:
  port: 8080
spring:
  application:
    name: cloud-consumer-order
#服务入驻
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://7001.cn.utools.club/eureka,http://7002.cn.utools.club/eureka