server:
  port: 8002

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 3333


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities       #所有Entity别名类所在包

#服务入驻
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://7001.cn.utools.club/eureka,https://7002.cn.utools.club/eureka
  instance:
    instance-id: payment-8002
    prefer-ip-address: true  #mouse hover时显示IP地址

    #Eureka客户端向服务器端发送心跳的时间间隔 ，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka 服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒）,超时剔除服务
    lease-expiration-duration-in-seconds: 2