server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        # 路由 1
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001   #匹配后提供服务的路由地址
          predicates:
            - Path=/provider/payment/get/**   #断言,路径相匹配的进行路由
        # 路由 2
        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/provider/payment/lb/**   #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://7001.cn.utools.club/eureka,https://7002.cn.utools.club/eureka
